### ISSUE TITLE
Some tools missing

### ISSUE THREAD

**Issue by ismael3d** [potree/PotreeConverter#404] opened 2020-04-22 09:41 UTC
I have created a point cloud web visualization but the following tools are not visible or available:
- circle measurement
- north angle measurement
- circular volume measurement
- annotation

Any idea about what happened?
I am doing this with potree converter 1.6

Thank you in advance

**Comment by midnight-dev** [comment] 2020-05-11 21:09
Hi there. The version of Potree that PotreeConverter used to generate a page is an older version. I believe @m-schuetz will release version 1.7 very soon, which will include these features. If you would like to have them, they're already available on the _develop_ branch of [potree/potree](https://github.com/potree/potree). You will need to replace the potree library located in `PotreeConverter\resources\page_template\libs\potree\` with a built version of the develop branch. Or, for your already-generated page, just replace the appropriate Potree assets with the latest versions.

If you need further assistance, lemme know. And be sure to check back in a couple weeks, because a new release is on the horizon. PotreeConverter will likely see some more attention soon after 🤞

**Comment by EucentreMM** [comment] 2020-05-30 14:53
> Hi there. The version of Potree that PotreeConverter used to generate a page is an older version. I believe @m-schuetz will release version 1.7 very soon, which will include these features. If you would like to have them, they're already available on the _develop_ branch of [potree/potree](https://github.com/potree/potree). You will need to replace the potree library located in `PotreeConverter\resources\page_template\libs\potree\` with a built version of the develop branch. Or, for your already-generated page, just replace the appropriate Potree assets with the latest versions.
> 
> If you need further assistance, lemme know. And be sure to check back in a couple weeks, because a new release is on the horizon. PotreeConverter will likely see some more attention soon after 🤞

Dear all, 
thank you for all the contributions!
I have tried to use PotreeConverter version 1.7, I tried to insert an annotation and some measurements. Then I exported the Scene (Export-Potree) and I tried the "Viewer.loadProject". When I load the new file.html I can see the measurements but not the annotations.

Thank you in advance!

**Comment by midnight-dev** [comment] 2020-06-16 02:53
> Dear all, 
> thank you for all the contributions!
> I have tried to use PotreeConverter version 1.7, I tried to insert an annotation and some measurements. Then I exported the Scene (Export-Potree) and I tried the "Viewer.loadProject". When I load the new file.html I can see the measurements but not the annotations.
> 
> Thank you in advance! 

@EucentreMM I think this has more to do with the core potree/potree project. PotreeConverter is the C++ point cloud writer which includes Potree for convenience. Your question would get more attention as an issue in the core repository.

Regardless, I'll try to help here. Did you use the same version of Potree when you exported the project as when you imported it with `loadProject()`? I ask because the save & load methods definitely attempt to save & load annotations. However, there may have been an inconsistency in the format between version 1.6 and 1.7 (beta). When I get back to my workstation, I'll look into this, but it would greatly help if you could share the exported JSON file and the console logs (if you know what these are - if not, that's okay).

**Comment by EucentreMM** [comment] 2020-06-16 16:46
> > Dear all,
> > thank you for all the contributions!
> > I have tried to use PotreeConverter version 1.7, I tried to insert an annotation and some measurements. Then I exported the Scene (Export-Potree) and I tried the "Viewer.loadProject". When I load the new file.html I can see the measurements but not the annotations.
> > Thank you in advance!
> 
> @EucentreMM I think this has more to do with the core [potree/potree](https://github.com/potree/potree) project. PotreeConverter is the C++ point cloud writer which includes Potree for convenience. Your question would get more attention as an issue in the core repository.
> 
> Regardless, I'll try to help here. Did you use the same version of Potree when you exported the project as when you imported it with `loadProject()`? I ask because the save & load methods definitely attempt to save & load annotations. However, there may have been an inconsistency in the format between version 1.6 and 1.7 (beta). When I get back to my workstation, I'll look into this, but it would greatly help if you could share the exported JSON file and the console logs (if you know what these are - if not, that's okay).

@midnight-dev 
Thank you very much for the answer and the support. I have checked and I could confirm to you that I have used Potree Converter 1.7. Once I have converted the point cloud, I exported the Json file and then I modified the html file adding the  `loadProject()' command.  Propably I did something wrong in editing the html file. Please find attached the JSON file and a screen of the html file. 
Thanks very much in advance.
Martina 
[Load_Project_issue.zip](https://github.com/potree/PotreeConverter/files/4787916/Load_Project_issue.zip)

**Comment by midnight-dev** [comment] 2020-06-17 13:53
@EucentreMM Hey Martina, so I took a peek. There's nothing wrong with your HTML. It's the JSON. There's just no annotation data inside it whatsoever. 

This means that no annotation is being exported when you try to save the project data. I'm going to have to look into this, because even with an older JSON that has valid annotations has trouble loading. 

The format and loader revisions may have broke the save functionality for annotations, and whatever changed is making the load feature skip over annotations anyway. Later today, I'll file a dedicated issue on the main repo if I don't find an existing one, and I'll link the issue here so you can follow it there.

@ismael3d Did the latest release address your original issue, or do you still have missing tools?

**Comment by EucentreMM** [comment] 2020-06-17 16:54
@midnight-dev thank you very much!

**Comment by midnight-dev** [comment] 2020-06-20 05:11
@EucentreMM Sorry for the delay, Martina. The last couple of days had a few unexpected events. 

I noticed something seems off with the current build's handling of annotations, but I don't think it actually relates to this issue. More to the point, I found there was a difference in export functions. While I assumed everything was saved regardless of format, my local build only saves annotation data if exporting in the _Potree_ format. The _JSON_ option only saves the measurements, which explains why it outputs a file named something like "measure.json" - on the other hand, the "potree.json" file contains basically everything. 

Try out the Potree export option that's located in the same area, on the right of JSON & DXF. Please lemme know if that works for you.

**Comment by EucentreMM** [comment] 2020-06-22 15:17
@midnight-dev 
Thank you for the support. 
I have tried to download the Potree.json file (as you kindly suggested). Even if the annotations are now present in the json file, loading the project  all the tools are loaded (measurements, section ...), with the excepiton of annotations (unfortunally).
Please find attached the Json file (if useful).
Thanks in advance,
Martina


[potree.zip](https://github.com/potree/PotreeConverter/files/4814049/potree.zip)

**Comment by midnight-dev** [comment] 2020-06-27 08:28
@EucentreMM I've been able to confirm that this unexpected behavior with annotations exists on the current build of Potree (using your JSON and my own saved Potree data too), but I need a bit more time to pinpoint if it's the import or export that's to blame. I'll open up a proper issue with relevant details; hopefully, I'll have a solution by then, though I'm going to be busy working at the office all weekend.

Sorry for the delay, as I initially thought this would pretty quick to diagnose. May be a few more days - stay tuned.

**Comment by patrimoniodigitale** [comment] 2020-07-02 18:43
Hi, i have a problem with a 1.6 version, the intensity doesn't upload
and in 1.7 version how "resources" folder i have to use?

**Comment by midnight-dev** [comment] 2020-07-03 00:48
> and in 1.7 version how "resources" folder i have to use?

@patrimoniodigitale Try copying the binary file (e.g. PotreeConverter.exe on Windows) from its original location `/PotreeConverter/` to the "resources" directory, meaning `/PotreeConverter/resources/`. Then run the binary file from that location (the resources folder) if you want to be able to generate HTML pages. 

If you don't need to or don't want to generate pages, you shouldn't have to do this. Regardless, you can try this anyway because having an extra executable file in a different directory should not create any unwanted side effects.

If you're seeing an error or warning message regarding resources, please post it with the issue.

**Comment by patrimoniodigitale** [comment] 2020-07-03 07:09
@midnight-dev thanks...

I copied the resources folder in to the binary file folder 

![filesorgente](https://user-images.githubusercontent.com/67730339/86441207-1fdc2600-bd0c-11ea-8e6d-d2e0033cebc9.JPG)

![2](https://user-images.githubusercontent.com/67730339/86441392-6df12980-bd0c-11ea-9370-6665bfaaafc9.JPG)

the conversion works, but now linear measurements doesn't works,
volumetric ones yes
![3](https://user-images.githubusercontent.com/67730339/86441530-a55fd600-bd0c-11ea-8a6a-9aceae68121e.JPG)

But if i use 1.6 version, works well the measurment but i don't have a intensity scalar field..

it possible to merge the both version?
if i change the "tool of measurment" from folder 1.6 to folder 1.7?
im a ignorant of this...
thanks a lot

**Comment by patrimoniodigitale** [comment] 2020-07-03 08:04
I have solved for now, with a 1.7beta version

**Comment by midnight-dev** [comment] 2020-07-04 04:22
@patrimoniodigitale Glad to hear that! Did it work for you only after re-running the 1.7beta converter on your point cloud data, or did you include the 1.7beta [core Potree JavaScript](https://github.com/potree/potree) build in the `/resources/page_template/libs/` path? 

I want to make sure the solution is clear for anyone experiencing this with an older pre-release. Depending on what actually fixed it, we could write up instructions on how to backport a patch to an older version if someone can't upgrade to the latest release. 👌

**Comment by patrimoniodigitale** [comment] 2020-07-04 08:14
Hi, i used directly the 1.7beta version...

Im testing the 1.7Desktp-master, work well for now, but it doesn't have a nodule_modules folder.. I imported the folder nodule_modules from PotreeDesktop_1.7PRE_2019.11.10_windows. 

And after for upload the project i had copied the libs folder from 1.7Desktp-master.

**Comment by patrimoniodigitale** [comment] 2020-07-04 08:15
i wrote a instructions but in italian language!!!

**Comment by m-schuetz** [comment] 2020-08-05 16:54
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.

**Closed by m-schuetz** 2020-08-05 16:54 UTC
