### ISSUE TITLE
Question : Random sampling and poisson

### ISSUE THREAD

**Issue by FrenchTrott** [potree/PotreeConverter#440] opened 2020-08-28 11:15 UTC
Hi Markus,
Question, what is the step/grid of this two filters ?
How we can custom the distance ?
or how does it work?

Thanks in advance,

BR

**Comment by m-schuetz** [comment] 2020-08-29 14:02
Random sampling uses a grid size of 128, and poisson-disk sampling uses a minimum distance of nodesize / 128. At the moment, these values are hardcoded, e.g.: https://github.com/potree/PotreeConverter/blob/9df10f452d9044fbacbc492bd2f05fb4ace90670/Converter/src/indexer.cpp#L1077

**Comment by FrenchTrott** [comment] 2020-08-29 14:16
Ok !
In test, two project dont work both with random or fish ...

An idea ?

Same error, duplicate points

**Comment by m-schuetz** [comment] 2020-08-29 14:20
Abort on too many duplicates was intentional but you could try to change following code:

https://github.com/potree/PotreeConverter/blob/9df10f452d9044fbacbc492bd2f05fb4ace90670/Converter/src/indexer.cpp#L899-L906

Instead of calling exit(), you could try to call "continue". I can't garuantee it will work, though. If you try it, please let me know if it did work. In any case, could you send me the smallest laz file that causes this issue?

**Comment by FrenchTrott** [comment] 2020-08-29 17:56
![image](https://user-images.githubusercontent.com/70017780/91643241-bc335800-ea31-11ea-9b50-877d21672575.png)

**Comment by m-schuetz** [comment] 2020-09-09 10:49
Closing this because it's a duplicate of https://github.com/potree/PotreeConverter/issues/438#issuecomment-689477023 and https://github.com/potree/PotreeConverter/issues/437

**Closed** 2020-09-09 10:49 UTC
