### ISSUE TITLE
Issue when compiling on Debian 10

### ISSUE THREAD

**Issue by loicroybon** [potree/PotreeConverter#455] opened 2020-09-21 10:44 UTC
Hell, 

I've this issue when I do "sudo make ../" 
```
CMake Error at CMakeLists.txt:54 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
```

How can I solve it please ?

**Comment by m-schuetz** [comment] 2020-09-21 10:45
Duplicate of #447

**Closed by m-schuetz** 2020-09-21 10:45 UTC
